# Generated by Django 2.2 on 2023-06-12 10:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('reply', models.CharField(max_length=200, verbose_name='回复')),
                ('like', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.CourseComments', verbose_name='评论内容')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '课程回复',
                'verbose_name_plural': '课程回复',
            },
        ),
        migrations.CreateModel(
            name='UserAllCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('course_type', models.CharField(choices=[('required', '必修课程'), ('progressing', '正在进行'), ('endding', '已结束')], max_length=10, verbose_name='课程类别')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程名')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '全部课程',
                'verbose_name_plural': '全部课程',
            },
        ),
        migrations.RemoveField(
            model_name='userfavorite',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserCourse',
        ),
        migrations.DeleteModel(
            name='UserFavorite',
        ),
    ]
