# Generated by Django 2.2 on 2023-06-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20230612_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='userallcourse',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='是否必修'),
        ),
        migrations.AlterField(
            model_name='userallcourse',
            name='course_type',
            field=models.CharField(choices=[('not_start', '未开始'), ('progressing', '正在进行'), ('endding', '已结束')], max_length=10, verbose_name='课程类别'),
        ),
    ]
