# Generated by Django 2.2 on 2023-06-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20230612_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='userallcourse',
            name='last_click_time',
            field=models.DateTimeField(null=True, verbose_name='上次点击时间'),
        ),
    ]
