# Generated by Django 2.2 on 2023-06-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseresource',
            name='is_audit',
            field=models.BooleanField(default=False, verbose_name='是否通过审核'),
        ),
        migrations.AddField(
            model_name='video',
            name='is_audit',
            field=models.BooleanField(default=False, verbose_name='是否通过审核'),
        ),
    ]
