# Generated by Django 2.2 on 2023-06-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20230612_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.CharField(default='', max_length=15, verbose_name='讲师'),
        ),
    ]
