# Generated by Django 2.2 on 2023-06-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='course',
            name='detail',
        ),
        migrations.AddField(
            model_name='course',
            name='introduce',
            field=models.TextField(default='', verbose_name='课程描述'),
        ),
    ]
