# Generated by Django 2.2 on 2023-06-12 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_auto_20230612_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentdetailopinion',
            name='document_audit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='audits.DocumentAudit', unique=True, verbose_name='审核文档'),
        ),
        migrations.AlterField(
            model_name='videodetailopinion',
            name='video_audit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='audits.VideoAudit', unique=True, verbose_name='审核视频'),
        ),
    ]
