# Generated by Django 2.2 on 2023-06-12 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_auto_20230612_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentaudit',
            name='document',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseResource'),
        ),
        migrations.AlterField(
            model_name='videoaudit',
            name='video',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Video'),
        ),
        migrations.AlterField(
            model_name='videodetailopinion',
            name='video_audit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='audits.VideoAudit', verbose_name='审核视频'),
        ),
    ]
