# Generated by Django 2.2 on 2023-06-12 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_auto_20230612_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentdetailopinion',
            name='document_audit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='audits.DocumentAudit', verbose_name='审核文档'),
        ),
    ]
